name: Fine-Tune and Evaluate (uv)

on:
  workflow_dispatch:

jobs:
  train:
    name: Fine-tune
    runs-on: [self-hosted, Linux, X64, wsl2]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv --version

      - name: Setup Python environment
        run: |
          uv venv --python 3.10
          uv sync --all-extras

      - name: Install Flash Attention
        env:
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv pip install flash-attn --no-build-isolation

      - name: Prepare dataset
        run: |
          uv run python prepare_data.py

      - name: Train (QLoRA)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv run python train.py

      - name: Upload adapters
        uses: actions/upload-artifact@v4
        with:
          name: lora-adapters
          path: ./avro-phi3-adapters/

  evaluate:
    name: Evaluate
    needs: train
    runs-on: [self-hosted, Linux, X64, wsl2]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv --version

      - name: Setup Python environment
        run: |
          uv venv --python 3.10
          uv sync --all-extras

      - name: Download adapters
        uses: actions/download-artifact@v4
        with:
          name: lora-adapters
          path: ./avro-phi3-adapters/

      - name: Install Flash Attention
        env:
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv pip install flash-attn --no-build-isolation

      - name: Evaluate
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv run python evaluate.py 2>&1 > evaluation_output.txt

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-report
          path: evaluation_output.txt
