name: Fine-Tune and Evaluate (uv)

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'  # Semantic version tags like 0.1.0 or v0.1.0
      - 'train-*'                  # Trigger on training tags like train-2024-01-15
      - 'exp-*'                    # Trigger on experiment tags like exp-larger-dataset

jobs:
  train:
    name: Fine-tune
    runs-on: [self-hosted, Linux, X64, wsl2]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv --version

      - name: Setup Python environment
        run: |
          uv venv --python 3.10
          uv sync --all-extras

      - name: Install Flash Attention
        env:
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv pip install flash-attn --no-build-isolation

      - name: Prepare dataset
        run: |
          uv run python prepare_data.py

      - name: Train (QLoRA)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv run python train.py

      - name: Upload adapters
        uses: actions/upload-artifact@v4.3.3  # Latest stable v4 version
        # Alternative: Use v3 for better compatibility
        # uses: actions/upload-artifact@v3
        with:
          name: lora-adapters
          path: ./avro-phi3-adapters/

  evaluate:
    name: Evaluate
    needs: train
    runs-on: [self-hosted, Linux, X64, wsl2]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv --version

      - name: Setup Python environment
        run: |
          uv venv --python 3.10
          uv sync --all-extras

      - name: Download adapters
        uses: actions/download-artifact@v4.1.7
        with:
          name: lora-adapters
          path: ./avro-phi3-adapters/

      - name: Install Flash Attention
        env:
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv pip install flash-attn --no-build-isolation

      - name: Evaluate
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          CUDA_HOME: /usr/local/cuda-12.8
          PATH: /usr/local/cuda-12.8/bin:$PATH
        run: |
          uv run python evaluate.py 2>&1 > /tmp/evaluation_output.txt
          # Display the output after capture
          cat /tmp/evaluation_output.txt

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: evaluation-report
          path: evaluation_output.txt
